---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  tags: [nginx, install]

- name: Enable and start nginx
  service:
    name: nginx
    enabled: yes
    state: started
  tags: [nginx, start]

- name: Create web page with hostname
  copy:
    dest: /var/www/html/index.html
    content: "<html><body><h1>{{ ansible_hostname }}</h1></body></html>"
  tags: [nginx, content]

- name: Generate self-signed TLS certificate directory
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0700'
    owner: root
    group: root
  tags: [nginx, ssl]

- name: Generate self-signed TLS certificate
  command: >
    openssl req -x509 -nodes -days 365
    -newkey rsa:2048
    -keyout /etc/nginx/ssl/nginx.key
    -out /etc/nginx/ssl/nginx.crt
    -subj "/CN={{ inventory_hostname }}"
  args:
    creates: /etc/nginx/ssl/nginx.crt
  tags: [nginx, ssl]

- name: Deploy custom HTTPS nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: 0644
    owner: root
    group: root
  notify: Reload nginx
  tags: [nginx, config]

